version: "3"
services:
  backend-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
    ports:
      - "${SQL_PORT}:1433"
    networks:
      - payrollAPI-network

  backend-api:
    build: .
    restart: on-failure
    depends_on: 
    - backend-db
    networks:
      - payrollAPI-network

networks:
  payrollAPI-network:
    driver: bridge